// src/components/EnforcerFormModal.jsx
import React, { useEffect, useState } from "react";

const initialForm = {
  idNumber: "",
  name: "",
  contact: "",
  address: "",
  photoFile: null,
};

export default function EnforcerFormModal({ show, onClose, onSubmit }) {
  const [form, setForm] = useState(initialForm);
  const [previewUrl, setPreviewUrl] = useState("");

  useEffect(() => {
    if (show) {
      setForm(initialForm);
      setPreviewUrl("");
    }
  }, [show]);

  if (!show) return null;

  const set = (key) => (e) => {
    const value =
      key === "photoFile" ? e.target.files?.[0] || null : e.target.value;

    setForm((prev) => ({
      ...prev,
      [key]: value,
    }));

    if (key === "photoFile") {
      setPreviewUrl(value ? URL.createObjectURL(value) : "");
    }
  };

  const canSubmit =
    form.name.trim() &&
    form.contact.trim() &&
    form.address.trim();

  async function handleSubmit(e) {
    e.preventDefault();
    if (!canSubmit) return;

    await onSubmit({
      idNumber: form.idNumber.trim(),
      name: form.name.trim(),
      contact: form.contact.trim(),
      address: form.address.trim(),
      photoFile: form.photoFile,
      apprehensionRecord: [],
    });
  }

  return (
    <div
      className="position-fixed top-0 start-0 w-100 h-100 d-flex justify-content-center align-items-center"
      style={{ background: "rgba(0,0,0,.35)", zIndex: 2000, padding: 16 }}
      onClick={onClose}
    >
      <div
        className="bg-white rounded-4 shadow-lg w-100"
        style={{
          maxWidth: 520,
          maxHeight: "90vh",
          overflow: "auto",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-4">
          <div className="d-flex align-items-center justify-content-between mb-3">
            <h2 className="h5 fw-bold mb-0">Enforcer Form</h2>

            <button
              className="btn btn-light rounded-circle"
              type="button"
              onClick={onClose}
            >
              ✕
            </button>
          </div>

          <form onSubmit={handleSubmit}>
            <div className="mb-3">
              <div className="small text-muted mb-1">Profile Picture</div>

              <div className="d-flex align-items-center gap-3">
                <div
                  className="rounded-circle d-flex align-items-center justify-content-center bg-light border"
                  style={{
                    width: 72,
                    height: 72,
                    overflow: "hidden",
                    flex: "0 0 auto",
                  }}
                >
                  {previewUrl ? (
                    <img
                      src={previewUrl}
                      alt="Enforcer preview"
                      style={{
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                      }}
                    />
                  ) : (
                    <i className="bi bi-person text-muted fs-3"></i>
                  )}
                </div>

                <input
                  className="form-control"
                  type="file"
                  accept="image/*"
                  onChange={set("photoFile")}
                />
              </div>
            </div>

            <div className="mb-3">
              <div className="small text-muted mb-1">ID Number</div>
              <input
                className="form-control bg-light border-0 rounded-4"
                value={form.idNumber}
                onChange={set("idNumber")}
                placeholder="Optional / generated by system"
              />
            </div>

            <div className="mb-3">
              <div className="small text-muted mb-1">Name</div>
              <input
                className="form-control bg-light border-0 rounded-4"
                value={form.name}
                onChange={set("name")}
              />
            </div>

            <div className="mb-3">
              <div className="small text-muted mb-1">Contact Number</div>
              <input
                className="form-control bg-light border-0 rounded-4"
                value={form.contact}
                onChange={set("contact")}
              />
            </div>

            <div className="mb-4">
              <div className="small text-muted mb-1">Address</div>
              <input
                className="form-control bg-light border-0 rounded-4"
                value={form.address}
                onChange={set("address")}
              />
            </div>

            <button
              className="btn btn-primary w-100 rounded-4 py-2"
              type="submit"
              disabled={!canSubmit}
            >
              Add
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}